### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by Rob--W** [Rob--W/open-in-browser#10]
Once the add-on is ready, I will replace the current AMO listing with my version.

The add-on listing needs to be updated though, and maybe also the README here.

@est31 Is this something that you would like to do?

**Comment by est31** [comment]
@Rob--W sure I can do it!

**Comment by est31** [comment]
The original XUL based extension has now a modern Browserextension version available, allowing you to continue to use it on Firefox versions 57 and later! The rewrite has resulted in some minor changes in the user interface and functionality.

Please file any bugs on GitHub: https://github.com/Rob--W/open-in-browser . Contributions are welcome as well!
