### ISSUE TITLE
Wrong window size and addon not working.

### ISSUE THREAD

**Issue by TheDcoder** [Rob--W/open-in-browser#16]
Hello, I have just upgraded to Firefox 57 on Windows 8.1.
First of all, kudos for porting this addon over to the WebExtensions API 👍

Sadly, it is not working for me... as you might have guessed but the title, the popup window's size is too small vertically.
![firefox_2017-11-18_14-11-52](https://user-images.githubusercontent.com/6347576/32978594-52a69a00-cc6b-11e7-949d-fea6699823e3.png)

And clicking the "OK" or "Cancel" button does nothing 😕. I tried this multiple times but these two issues can be reproduced every time.

P.S Sorry for creating a single issue, but I wasn't sure that the issues were not related.

**Comment by Rob--W** [comment]
Did the dialog show `From: (empty)` as seen in the screenshot? If so, that suggests that a script error occurred while executing `dialog.js` (on the other hand, "What should Firefox do with this file" shows up as expected, so `i18n.js` did run as expected).

Can you open the global JS console (Ctrl - Shift -J) and see if there are any error messages?

**Comment by TheDcoder** [comment]
There are indeed multiple errors:
![firefox_2017-11-18_16-50-58](https://user-images.githubusercontent.com/6347576/32979718-bb22bbda-cc80-11e7-9957-75a10630455a.png)
A copy of the error text:
```
mime_getFriendlyName
moz-extension://200789be-6226-416f-8120-47fbe52f7c6c/mime-metadata.js:18:2
mime_getFriendlyName
moz-extension://200789be-6226-416f-8120-47fbe52f7c6c/mime-metadata.js:33:9
mime_getFriendlyName
moz-extension://200789be-6226-416f-8120-47fbe52f7c6c/mime-metadata.js:33:9
mime_getFriendlyName
<insert a lot of same stuff with mention of line 33 and column 9>
mime_getFriendlyName
moz-extension://200789be-6226-416f-8120-47fbe52f7c6c/mime-metadata.js:33:9
mime_getFriendlyName
moz-extension://200789be-6226-416f-8120-47fbe52f7c6c/mime-metadata.js:33:9
mime_getFriendlyName
```

**Comment by Rob--W** [comment]
Thanks for the report, I fixed it in version 2.2. I wonder, how did you manage to get an empty UI language?

**Comment by TheDcoder** [comment]
Looks like you fixed it @Rob--W, I have some news which is surprising, after restarting my laptop, the extension seems to work fine... should have mentioned it as soon as I noticed it.

**Comment by TheDcoder** [comment]
> I wonder, how did you manage to get an empty UI language?

No idea, it might have been a Firefox bug as the issue seemed to be resolved after a restart. Not surprising considering that FF 57 was the first release to feature the new "Quantum" engine :slightly_smiling_face:
