### ISSUE TITLE
Better/more MIME sniffing

### ISSUE THREAD

**Issue by arantius** [Rob--W/open-in-browser#23]
Open https://bugs.centos.org/view.php?id=2137 and click the "strace_pwd.txt" link.

The default is "server sent mime"*, but leaving that selected and pressing OK just gives me a download prompt.  The extension is ".txt" and opening as text works, so I'd prefer that to be the default choice.

\* The server sent `Content-Type: text/x-c; charset=us-ascii` which is not a MIME type that Firefox will choose to display.

**Comment by Rob--W** [comment]
I pushed a commit. This is a minor issue, so I'm not going to push an update right away.

If you see yourself opening such files quite often, you can remember the action to open it inline as Text.

**Comment by arantius** [comment]
Thanks for the amazingly fast fix!  I want something similar for PDF but I need to make a good report for it; maybe a pull request.
