### ISSUE TITLE
Make the order of buttons configurable

### ISSUE THREAD

**Issue by rbrito** [Rob--W/open-in-browser#24]
I am using the MATE desktop environment under Linux and I migrated to this extension after I upgraded to Firefox 57.
 
It works well so far, but there is one thing that I would like the extension to do: match the way that my desktop environment places the OK button on the **right** of the Cancel button, instead of the current behavior that I see (see attached screenshot).

![screenshot at 2017-11-22 19-28-51](https://user-images.githubusercontent.com/212145/33153074-1f3fc5ba-cfc7-11e7-9ff1-7510f4b0b8b7.png)

This is important for usability purposes, since I have already mistakenly clicked rapidly on the button on the right (which only after the fact I realized that it was the Cancel button) and didn't notice that I had not downloaded a file. 😢

Thanks,

Rogério Brito.

**Comment by Rob--W** [comment]
Fixed in 2.4.

**Comment by rbrito** [comment]
Thanks a lot @Rob--W.
