### ISSUE TITLE
When downloading a file, there are two save dialogs

### ISSUE THREAD

**Issue by HighCommander4** [Rob--W/open-in-browser#30]
With this extension installed, when I download any file, I get two dialogs. 

Here is the first dialog:

![open-in-browser-dialog1](https://user-images.githubusercontent.com/1751085/34221946-cd878f56-e587-11e7-9ade-927e89dca2eb.png)

After I select "Save File" in the first dialog, I get the second dialog:

![open-in-browser-dialog2](https://user-images.githubusercontent.com/1751085/34221968-e5913e80-e587-11e7-8fb7-95262344654c.png)

where I need to select "Save File" again.

Is it possible to avoid having to click through two dialogs that are basically the same?

**Comment by Rob--W** [comment]
This was reported before in #25 and addressed by c9cf2e00ed445846de8ee8f89fbab947a421e261.

I have documented this in the add-on description on AMO (https://addons.mozilla.org/en-US/firefox/addon/open-in-browser/) and also briefly at the preferences page. What else can I do to make this option more discoverable?

**Comment by HighCommander4** [comment]
> This was reported before in #25 and addressed by c9cf2e0.

Thanks. I can confirm that the workaround works.

> I have documented this in the add-on description on AMO (https://addons.mozilla.org/en-US/firefox/addon/open-in-browser/) and also briefly at the preferences page. What else can I do to make this option more discoverable?

I think that's good enough. I'm just an early user of the addon who installed it before the add-on description mentioned that workaround.

**Comment by Rob--W** [comment]
@HighCommander4  Is the issue specific to the Firefox profile, or to the machine? To test you could copy the profile directory from one machine to another and check if the behavior is consistent.

**Comment by ozmium** [comment]
This bug is still happening on the Mac, even when the workaround is applied from the instructions.

A good example is here: 

https://www.jetbrains.com/pycharm/download/?fromIDE=#section=mac

Click the link to download any of the DMG files (for Mac) from that page. **You will always get 2 download popup dialogs**, no matter what settings you have applied to 'Open In Browser'.
