### ISSUE TITLE
Download popup appears on nydailynews.com

### ISSUE THREAD

**Issue by mulad** [Rob--W/open-in-browser#33]
I'm getting a download popup from this plugin when attempting to visit http://www.nydailynews.com/news

Looks like another page that does not send the Content-Type header.
 
![image](https://user-images.githubusercontent.com/2359144/34911887-ced55a18-f898-11e7-9d16-225ba326dbed.png)

**Comment by Rob--W** [comment]
I'm going to not show a dialog for documents in frames without type. Have you encountered any other instances of this issue (or other similar situations like #31 or #32)?

**Comment by mulad** [comment]
I've seen the same problem on internal websites at my company. This was the first public site where I saw it.

**Comment by Rob--W** [comment]
Was that for frames (e.g. this bug) or for the main (top-level) page (e.g. the other bugs that I linked)?
