### ISSUE TITLE
Download dialog shown on maskray.me (duplicated content-type)

### ISSUE THREAD

**Issue by yan12125** [Rob--W/open-in-browser#34]
Full URL: https://maskray.me/blog/2016-03-13-terminal-emulator-fullwidth-color-emoji

When Accept-Language is included in the request header, response headers have duplicated content-type headers. The first is application/octet-stream. If I disabled open-in-browser, the page is correctly shown. Looks like Firefox checks the last header while open-in-browser use the first one.
```
$ curl --head 'https://maskray.me/blog/2016-03-13-terminal-emulator-fullwidth-color-emoji' -H 'Accept-Language: zh-TW,en-US;q=0.7,en;q=0.3'                                                                             
HTTP/2 200 
server: nginx/1.13.7
date: Wed, 07 Feb 2018 12:54:44 GMT
content-type: application/octet-stream
content-length: 29476
last-modified: Mon, 15 Jan 2018 04:50:52 GMT
etag: "5a5c332c-7324"
content-type: text/html
vary: Accept-Language
accept-ranges: bytes
```

**Comment by Rob--W** [comment]
Thanks for the clear report. I have committed a fix.
