### ISSUE TITLE
http://bip.umwd.dolnyslask.pl/plik,id,12899

### ISSUE THREAD

**Issue by def00111** [Rob--W/open-in-browser#35]
attachment; filename="ROZPORZ¥DZENIE PREZESA RADY MINISTRÓW z dnia 9 kwietnia 2009 r. w sprawie okrelenia wzorów formularzy owiadczeñ ma.rtf"

Your getFilenameFromContentDispositionHeader will not decode the filename correctly.

"iso-8859-1" works for me:
"ROZPORZ¥DZENIE PREZESA RADY MINISTRÓW z dnia 9 kwietnia 2009 r. w sprawie okreœlenia wzorów formularzy oœwiadczeñ ma.rtf"

**Comment by Rob--W** [comment]
The original URL is no longer available, but I managed to recreate a test case based on your report. Thanks for the report and patch!
