### ISSUE TITLE
Doesn't remember settings after closing firefox

### ISSUE THREAD

**Issue by ghost** [Rob--W/open-in-browser#39]
Hello, thank you for this great addon!

I noticed that after I close browser all my settings and remembered actions are lost. How are they stored? Indexeddb, local storage or anything else?

I use CookieAutoDelete which clear cookies and localstorage but shouldn't touch extensions data.

Firefox 59

**Comment by FedericoYundt** [comment]
It seems both:

- [CookieAutoDelete](https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/) -> Settings -> Localstorage cleanup
- Firefox Preferences -> Privacy & Security -> History -> Clear history when Firefox closes -> Offline Website Data

Result in clearing this addon settings. I use dozens of addons but this one is first affected by those. I see you [already have a plan](https://github.com/Rob--W/open-in-browser/issues/11) to migrate to `browser.storage` so feel free to close this if you don't want this separate issue.

**Comment by Rob--W** [comment]
Fixed in 2.7.
