### ISSUE TITLE
Highlight "save file" by default (or customize option)

### ISSUE THREAD

**Issue by jimbo1qaz** [Rob--W/open-in-browser#40]
After this addon is installed, the default option in the file-save dialog is "open in browser". For unopenable files, this pops up the browser's native file-save dialog (despite browser.helperApps.neverAsk.saveToDisk). For openable files, the file is never saved.

This still occurs after clicking a download link, "save", OK, and clicking the link again.

Is it possible for me to highlight "save file" by default, but leave ^ as an option?

**Comment by Rob--W** [comment]
What is `^` ?

Do you mean to show "Save As" by default, and allow the arrow-up key to be used to choose a previous option? I have already implemented this (3cad66cc69136212118f58d64d8052f59a79de2e), but I somehow forgot to publish the update on AMO.

**Comment by Rob--W** [comment]
I have published 2.6. It will still show "Open With" by default, but if you have chosen to download a file, then the "Save as" option will be selected by default. Can you try the new version and report if it addresses your issue?

**Comment by jimbo1qaz** [comment]
3cad66c description:

>select the "Save As" option by default if the most recent action was "Save As".

I'm not sure, IMHO "save as" should always be highlighted, even if you just opened a file in the browser. Is that how it worked in the non-webext version?

Nonetheless this is good enough 90% of the time.
