### ISSUE TITLE
Settings import/export

### ISSUE THREAD

**Issue by Mathnerd314** [Rob--W/open-in-browser#41]
Since the mime type associations can be somewhat cumbersome to set up by hand, it would be nice to have a way to save / load them from a file.

For inspiration you could look at uBlock, it has ['back up to file'](https://github.com/gorhill/uBlock/blob/dd49e0ad7cc5766c72c28daf8cbe9f2a156dc267/src/js/settings.js#L107) and ['restore from file'](https://github.com/gorhill/uBlock/blob/dd49e0ad7cc5766c72c28daf8cbe9f2a156dc267/src/js/settings.js#L36) features.

**Comment by Rob--W** [comment]
Sounds like a good feature, and helpful for cases like #39.
