### ISSUE TITLE
Download dialog should not appear in Recently Closed Windows

### ISSUE THREAD

**Issue by Lekensteyn** [Rob--W/open-in-browser#43]
When the download dialog is shown, it creates a new entry under *History* -> *Recently Closed Windows*. That history becomes quite of useless as <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>N</kbd> will now always open a defunct Open in Browser dialog.

Expected behavior: the Open in Browser dialog should not appear under *Recently Closed Windows*.

**Comment by Rob--W** [comment]
Fixed in 2.7.
