### ISSUE TITLE
SeaMonkey support

### ISSUE THREAD

**Issue by mittorn** [Rob--W/open-in-browser#44]
Is it possible to add seamonkey support? It has same download dialog, but extension installs and does not work

**Comment by Rob--W** [comment]
The current add-on is written using the WebExtensions framework, which is not supported by Seamonkey: https://www.seamonkey-project.org/releases/seamonkey2.49.2/#issues

> SeaMonkey does not currently support the WebExtensions add-on api. Some popular add-ons like NoScript are no longer shown because of this on the SeaMonkey add-ons website. You can usually get them from the manufacturers site if you can't find them on AMO. This will be addressed when the SeaMonkey and Thunderbird add-ons move to their own site. WebExtensions support is also a planned feature but will likely not appear in 2018.

Try the XUL-based addon: https://addons.mozilla.org/en-US/firefox/addon/open-in-browser/versions/1.18
Source code for the XUL-based version: https://github.com/spasche/openinbrowser
