### ISSUE TITLE
Export button is not working

### ISSUE THREAD

**Issue by Nalapl3** [Rob--W/open-in-browser#46]
Export button does nothing for me, but import button shows me a file dialog. There is no output in developer console.
I'm on Firefox Quantum 62.0.3, Windows 7 x64.

**Comment by Rob--W** [comment]
The "Export" button only does something when you have selected the "Export as file" or "Export as text" option. I just tried both of these options on Linux, and they both work as intended.

Can you state whether you have selected one of these options?

**Comment by Nalapl3** [comment]
I don't have these options at all.
https://i.imgur.com/VRdHKYz.png

**Comment by Rob--W** [comment]
Published update; thanks again for reporting the bug.
