### ISSUE TITLE
"Do this automatically" NW - Settings not saved for qif (firefox)

### ISSUE THREAD

**Issue by piecevcake** [Rob--W/open-in-browser#58]
Open in FF selected - not saved.
![FF open in browser resizing+not remembering setting for qif files @2019 05 18, 11_46_22](https://user-images.githubusercontent.com/32110576/57962737-fd077a80-796e-11e9-9dfe-65bd13a67b6f.png)

**Comment by Rob--W** [comment]
I overlooked this issue before, apologies for the late fix. I've fixed this issue in version 2.11.
