### ISSUE TITLE
perf.rust-lang.org false positive

### ISSUE THREAD

**Issue by est31** [Rob--W/open-in-browser#67]
The extension triggers for https://perf.rust-lang.org despite there being no reason to trigger it.

**Comment by Rob--W** [comment]
Duplicate of #32 and #61.

This site does not send any `Content-Type` header. For a work-around, see https://github.com/Rob--W/open-in-browser/issues/61#issuecomment-535392064

**Comment by est31** [comment]
I'll close it then as it's a dupe. Thanks!

**Comment by Rob--W** [comment]
I have reported this as a bug to https://github.com/rust-lang/rustc-perf/issues/784
