### ISSUE TITLE
Unable to get working

### ISSUE THREAD

**Issue by jeff-hykin** [Rob--W/open-in-browser#80]
I think I might be missing something as I simply never get a pop up or any kind of change in behavior.

 - Firefox 121.0.1
 - Restarted Firefox after installation
 - Set "Run on sites with restrictions" to true (tried both true and false)
 - MacOS 12.6 on an M1 chip
 - Tried toggling `browser.download.improvements_to_download_panel` (tried both true and false)
 
I tried pasting a local file:///some.csv file into the URL and also tried having a local csv file as a href in an anchor tag. Both just immedately get the default download-or-open prompt. Neither accepting or refusing the prompt triggers the open-in-browser extension.

**Comment by Rob--W** [comment]
The extension only works with http(s) URLs, not with file:-URLs.

If you want to view a file inline, you could consider adding `view-source:` in front of the URL. E.g. `view-source:file:///tmp/some.csv`

**Comment by jeff-hykin** [comment]
Thank you! That's exactly what I needed
