### ISSUE TITLE
Doesn't open in browser

### ISSUE THREAD

**Issue by arantius** [Rob--W/open-in-browser#9]
1. Navigate to https://boardgamegeek.com/filepage/33426/english-rules-kind-permission-chili-spiele
2. (Log in and) click the "Rules_Climbers02.pdf" link.
3. Get the (2.0beta5) open in browser dialog
4. Click "open in browser".
5. Get Firefox download UI

In Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

P.S. Please publish this even only as a beta version, it's still the best option I know of!

**Comment by Rob--W** [comment]
I don't have an account. Could you look at the response URL & headers and paste them here?

**Comment by arantius** [comment]
With no OiB extension clicking the PDF link gives:

https://boardgamegeek.com/file/download/3qot68ays4/Rules_Climbers02.pdf

    HTTP/1.1 302 Moved Temporarily
    Server: nginx/1.12.2
    Date: Sun, 12 Nov 2017 03:34:22 GMT
    Content-Type: text/html
    Transfer-Encoding: chunked
    X-Powered-By: PHP/5.5.38
    Set-Cookie: SessionID=REDACTED; expires=Sun, 12-Nov-2017 04:34:22 GMT; Max-Age=3600; path=/; domain=.boardgamegeek.com
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    Pragma: no-cache
    Location: http://files.geekdo.com/geekfile_download.php?filetype=bad%2Ftype&filename=Rules_Climbers02.pdf&filecode=3qot68ax1d&validationcode=REDACTED
    X-FastCGI-Cache: BYPASS

(Note manually redacted bits.)  Then

http://files.geekdo.com/geekfile_download.php?filetype=bad%2Ftype&filename=Rules_Climbers02.pdf&filecode=3qot68ax1d&validationcode=0475fb222ed31f07c7f048edfeabf016
 
    HTTP/1.1 200 OK
    Server: nginx/1.12.2
    Date: Sun, 12 Nov 2017 03:34:23 GMT
    Content-Type: bad/type
    Transfer-Encoding: chunked
    Connection: keep-alive
    X-Powered-By: PHP/5.3.3
    Content-Description: File Transfer
    Content-Disposition: attachment; filename="Rules_Climbers02.pdf"
    Content-Transfer-Encoding: binary
    Cache-Control: max-age=15552000
    Expires: Fri, 11 May 2018 03:34:23 GMT
    Vary: Accept-Encoding,User-Agent
    Content-Encoding: gzip

Maybe the redirect?  The content type is also fishy.

**Comment by Rob--W** [comment]
I just noticed the following step in your initial report:

> Get the (2.0beta5) open in browser dialog

Note that I haven't published my extension yet, the thing that you see on AMO is https://github.com/spasche/openinbrowser. Did you test my extension or the current beta on AMO?

I haven't tested, but based on the response headers I expect my extension to display the content in the browser if you choose "Open in browser as: application/pdf" (I intend to add an extra option "PDF")

**Comment by est31** [comment]
> Did you test my extension or the current beta on AMO?

@arantius has filed an issue on my repo previously, so I think it was the beta on AMO.

**Comment by arantius** [comment]
Ok, second try:

1. Remove any OiB version.
2. Check out this repo's master
3. Open about:debugging
4. Open checked out source as temporary extension
5. Start original steps

I get a window smaller than the min/max/close controls.  "Open in browser as" is checked, "server sent mime" is default which won't work (causes "geekfile_download.php" download dialog), PDF isn't one of the choices.

**Comment by Rob--W** [comment]
> I get a window smaller than the min/max/close controls.

This is #2 

> "Open in browser as" is checked, "server sent mime" is default which won't work (causes "geekfile_download.php" download dialog),

The server-sent MIME in your example is "bad/type". Of course a download dialog opens, because Firefox is unable to display it inline.

> PDF isn't one of the choices.

Fixed by adding "PDF" to the dropdown. Note that even without the option, you can choose "Other" and then "application/pdf" (or any other MIME)
